---
title: "Final Project Proposal"
author: "Group 5: Seungah Lee, Kedell Guevara, Jonathan Degardner, Malik Bulur, Varun Vepa"
date: "10/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Global Climate Change

### Dataset
https://www.kaggle.com/theworldbank/world-bank-climate-change-data

### Motivation of Study
The main goal of this project is to identify current global trends in climate change. Climate change has been seen as a variety of phenomena in the long run. It can be global warming or precipitation changes. Climate change has a direct and indirect impact on our daily lives, so it is necessary to recognize its seriousness and importance from a long-term perspective. A given dataset will be utilized to investigate changes in temperature and precipitation for different countries worldwide, and additional datasets such as rising sea levels will be used later on.

### Overview of Dataset
The World Climate Change data on Kaggle contains three large Excel workbooks with multiple sheets each. Each workbook/sheet covers an aspect important to climate change. The first workbook focuses on historical data pertaining to precipitation and temperature across many countries and regions. The second contains projections of change in temperature and change in precipitation for many years and countries, and the last covers multiple series of data such as CO2 emissions per capita, GDP and population for said countries across many years. We therefore have access to much information which will be helpful in us answering our questions about climate change.

### Brief Plan for Exploratory Analysis
The following questions will be answered to further analyze the dataset and related topics:

- What is a trend for the dataset? What trend has global climate change changed in terms of temperature, precipitation, sea level, and CO2 emissions over the past century?

- Is there a link between changes in precipitation and sea level?

- Is there a relationship between countries with higher median income groups and the rate of median changing temperature?

- Is there a link between sea level and income levels of a country?

- Is there a relation between median yearly temperature change and the influx of people moving to more urban areas? If so, which regions and/or countries are experiencing this relation the greatest?

- Does the average median temperature change increase or decrease the average annual precipitation seen by the world? How about by region?  

- Since 1990 to 2009 are there more people as a percentage experiencing extreme weather (Ex. Droughts, Floods, Extreme Temps)? Are there any countries and/or regions where the opposite is seen?

- Is the projected future data for the world show for more annual hot days and nights or more annual colder days and nights? Does a particular region of the world play a role in how this projection may play out?
Is methane (CH4) causing annual global median temperatures to increase? Which countries produce the most methane? How about the least? Compare the two groups to see exactly how much methane contributes to global warming.